export const TERMINOLOGY = {
  PAGE_NAMES: {
    // Admin page titles
    overview: "Tổng quan hệ thống",
    channel: "Phân tích theo kênh",
    conversation: "Quản lý hội thoại",
    aiinsights: "Phân tích AI",
    keyword: "Phân tích Keywords",
    sentiment: "Phân tích cảm xúc",
    chartbuilder: "Trình tạo biểu đồ",
    chatbot_sheet: "Quản lý thư viện phản hồi",
    settings: "Cài đặt hệ thống",

    // Staff page titles
    conversation_staff: "Hội thoại của tôi",
    faq_staff: "FAQ",
    chatbot_sheet_staff: "Thư viện phản hồi của tôi",
    performance_staff: "Hiệu suất cá nhân",
    profile_staff: "Hồ sơ cá nhân",
  },
  MENU_LABELS: {
    overview: "Tổng quan",
    channel: "Kênh",
    conversation: "Hội thoại",
    aiinsights: "Phân tích AI",
    keyword: "Keywords",
    sentiment: "Cảm xúc",
    chartbuilder: "Biểu đồ",
    chatbot_sheet: "Thư viện phản hồi",
    settings: "Cài đặt",
    
    // Staff extra
    faq: "FAQ",
    performance: "Hiệu suất",
    profile: "Hồ sơ",
  },
  ROLES: {
    manager: "Quản lý CSKH",
    staff: "Nhân viên CSKH",
    customer: "Khách hàng",
    student: "Sinh viên",
  },
  STATUS: {
    pending: "Chờ xử lý",
    processing: "Đang xử lý",
    completed: "Hoàn thành",
    waiting_manager: "Chờ quản lý xác nhận",
    waiting_approval: "Chờ duyệt",
    approved: "Đã duyệt",
    rejected: "Bị từ chối",
    need_edit: "Cần chỉnh sửa",
    success: "Thành công",
    failed: "Thất bại",
    active: "Đang hoạt động",
    inactive: "Tạm khóa",
    no_permission: "Không có quyền truy cập",
    priority_low: "Ưu tiên thấp",
    priority_medium: "Ưu tiên trung bình",
    priority_high: "Ưu tiên cao",
  },
  BUTTONS: {
    apply: "Áp dụng",
    reset: "Đặt lại",
    refresh: "Làm mới",
    save: "Lưu",
    save_changes: "Lưu thay đổi",
    cancel: "Hủy",
    close: "Đóng",
    confirm: "Xác nhận",
    view_details: "Xem chi tiết",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    approve: "Duyệt",
    reject: "Từ chối",
    request_edit: "Yêu cầu chỉnh sửa",
    add: "Thêm",
    add_faq: "Thêm vào FAQ",
    add_sheet: "Thêm phản hồi",
    resolve: "Đánh dấu đã xử lý",
    mark_ai_wrong: "Đánh dấu AI sai",
    send_corrected: "Gửi lại câu trả lời",
    send_manager: "Chuyển quản lý kiểm duyệt",
    back: "Quay lại",
    logout: "Đăng xuất",
  },
  AI: {
    success: "AI trả lời thành công",
    failed: "AI trả lời thất bại",
    wrong: "AI trả lời sai",
    uncertain: "AI không chắc chắn",
    hallucination: "AI có nguy cơ tự tạo thông tin",
    missing_data: "Không tìm thấy dữ liệu",
    need_review: "Cần kiểm duyệt",
    confidence: "Mức độ tin cậy",
    error_reason: "Lý do lỗi AI",
    intervention: "Can thiệp AI",
    kb: "Cơ sở tri thức",
    add_kb: "Bổ sung vào cơ sở tri thức",
    suggested_faq: "FAQ đề xuất",
    missing_faq: "FAQ cần bổ sung",
  }
};
